### ISSUE TITLE
Workstation GUI

### ISSUE THREAD

**Issue by bcroden** [bcroden/LMS#10]
The initial draft of the Workstation GUI is up. It doesn't currently do anything, but the layout is done.

This is absolutely not the final design, I just went with one that would allow us to test everything at once without spending too much time on the UI for release 1.

**Comment by bcroden** [comment]
The GUI is now up and running, I have commented out all of the code to where the workstation is supposed to connect to and talk with the DBM since I do not have the Database on my machine. As far as I know it should work, but it needs to be tested.

**Comment by bcroden** [comment]
Tested, and working.

**Comment by rxm033** [comment]
YAYYYYYYYYYYYYYY
