### ISSUE TITLE
Need to Define Networking Protocol

### ISSUE THREAD

**Issue by bcroden** [bcroden/LMS#7]
@alexv-anderson We probably need to define a proper networking protocol for the Workstation-DBM communications. Here are my 2 cents on what I think would work.

I have also uploaded a simple version of this networking protocol in the RSACipher's main function.

Definitions:
A message is defined as an integer value representing the size of the message, and a byte[] containing encrypted bytes. The integer value is sent first, allowing the receiver to create a byte[] of that size to contain the rest of the message. The byte[] is then sent and the receiver saves it to their allocated byte[]. 

Protocol:
The TCP Connection is established.
-Client: Creates a new RSACipher.
-Client: Sends a message containing their unencrypted Public RSA key to the server.
-Server: Creates a new RSACipher using the client's key.
-Server: Creates a new AESCipher.
-Server: Encrypts the AES key from the AESCipher with the RSACipher.
-Server: Sends a message containing the encrypted AES Key.
-Client: Decrypts the AES key with their RSACipher.
-Client: Creates a new AESCipher using the decrypted AES key.

The Client and Server now have access to the same AES key which they can then use to send encrypted messages back and forth.

A message needs to be sent.
-Sender: Generates a message in the form of a String.
-Sender: Encrypts the message with their AESCipher.
-Sender: Sends the encrypted message.
-Receiver: Decrypts the message with their AESCipher.
-Receiver: Processes the decrypted message.

**Comment by alexv-anderson** [comment]
The protocol you suggested looks good. I pushed a client/server that follows this protocol earlier today.
